# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<-SCRIPT
#centos7-base默认配置了 使用163的centos源 
#sudo mv /etc/yum.repos.d/CentOS-Base.repo /etc/yum.repos.d/CentOS-Base.repo.backup 
#sudo wget http://mirrors.163.com/.help/CentOS7-Base-163.repo -O /etc/yum.repos.d/CentOS-Base.repo


#======================安装方式1============================
#生成缓存
sudo yum makecache fast 
#Delta RPMs disabled because /usr/bin/applydeltarpm not installed  增量rpm包相关
sudo yum provides '*/applydeltarpm'
sudo yum install -y deltarpm 
#升级包和内核
sudo yum -y update

#yum-util 提供yum-config-manager功能
sudo yum install -y -q yum-utils 
#添加docker的repo
sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
sudo yum install -y docker-ce

#======================安装方式2=================================
#安装docker 
#sudo wget -qO- https://get.docker.com | sh 
#======================安装完成==================================

#设置docker服务启动后自运行 启动docker服务
sudo systemctl enable docker && sudo systemctl start docker

#设置mirror
#开放管理端口映射237 5为主管理端口，unix:///var/run/docker.sock用于本地管理，7654是备用的端口
sudo echo "====set docker manager port and mirror start===="
sudo sed -i -e 's!^ExecStart=/usr/bin/dockerd!ExecStart=/usr/bin/dockerd -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock -H tcp://0.0.0.0:7654 --registry-mirror=https://docker.mirrors.ustc.edu.cn!' /lib/systemd/system/docker.service
sudo echo "====set docker manager port and mirror end====" && sudo systemctl daemon-reload

sudo echo 'export DOCKER_HOST=tcp://0.0.0.0:2375' >> /etc/profile  
sudo echo "====docker host====" && source /etc/profile

sudo systemctl restart docker

#添加vagrant用户添加到docker权限组
sudo usermod -aG docker vagrant 

#默认的公钥在启动的时候会被移除（在vagrant up的时候可以看到下面的提示信息），如果需要自己生产公私钥，去掉这一行
#default: Vagrant insecure key detected. Vagrant will automatically replace
#default: this with a newly generated keypair for better security.
#default:
#default: Inserting generated public key within guest...
#default: Removing insecure key from the guest if it's present...
#default: Key inserted! Disconnecting and reconnecting using new SSH key...
curl https://raw.githubusercontent.com/mitchellh/vagrant/master/keys/vagrant.pub >> /home/vagrant/.ssh/authorized_keys

#测试docker安装结果  查看安装版本
docker -v
#拉取hello-world镜像
docker pull hello-world
#运用hello-world容器
docker run hello-world

#清理包
sudo yum clean all
SCRIPT

Vagrant.configure("2") do |config|
	#设置虚拟机的box
	config.vm.box = "centos7-base"
	
	#设置虚拟机的主机名
	config.vm.hostname = "centos7-base-docker"
	
	#Virtualbox相关配置
	config.vm.provider "virtualbox" do |v|
		#设置虚拟机的名称
		v.name = "centos7-base-docker"
		
		#设置虚拟机的内存大小为2G
		v.memory = 2048 
		
		#设置虚拟机的CPU个数
		v.cpus = 2 
	end 
	
	#使用shell脚本进行软件安装和配置
	config.vm.provision "shell", inline: $script 
	
end
